#docker-compose.yml
version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: myhotel_sql
    environment:
      SA_PASSWORD: "${SQL_PASSWORD}"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 90s
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql

  server:
    build: ./server
    container_name: myhotel_server
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=Hotel;User Id=sa;Password=${SQL_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=True;"
    ports:
      - "5017:5017"

  gateway:
    build: ./hotel-management-gateway
    container_name: myhotel_gateway
    depends_on:
      - server
    ports:
      - "3000:3000"

  client:
    build: ./client
    container_name: myhotel_client
    depends_on:
      - gateway
    ports:
      - "80:80"

volumes:
  sql_data: