// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(MyHotelDbContext))]
    [Migration("20260519140454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("server.Model.Condition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid?>("RegisteredsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredsId");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("server.model.PricesList", b =>
                {
                    b.Property<int>("IdPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrice"));

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid?>("RegisteredsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPrice");

                    b.HasIndex("RegisteredsId");

                    b.ToTable("PricesLists");
                });

            modelBuilder.Entity("server.model.PricesListHistory", b =>
                {
                    b.Property<int>("IdHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistory"));

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPrice")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("IdHistory");

                    b.ToTable("PricesListHistories");
                });

            modelBuilder.Entity("server.model.Registereds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SumPlace")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomLocationId");

                    b.ToTable("Registereds");
                });

            modelBuilder.Entity("server.model.RoomLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoomLocations");
                });

            modelBuilder.Entity("server.model.RoomsDB", b =>
                {
                    b.Property<int>("RoomNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomNum"));

                    b.Property<bool>("Extrta")
                        .HasColumnType("bit");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Occupied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnSea")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RoomLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomNum");

                    b.HasIndex("RoomLocationId");

                    b.ToTable("RoomsDBs");
                });

            modelBuilder.Entity("server.Model.Condition", b =>
                {
                    b.HasOne("server.model.Registereds", null)
                        .WithMany("ListConditions")
                        .HasForeignKey("RegisteredsId");
                });

            modelBuilder.Entity("server.model.PricesList", b =>
                {
                    b.HasOne("server.model.Registereds", null)
                        .WithMany("ListOptions")
                        .HasForeignKey("RegisteredsId");
                });

            modelBuilder.Entity("server.model.Registereds", b =>
                {
                    b.HasOne("server.model.RoomLocation", null)
                        .WithMany("ListRegistereds")
                        .HasForeignKey("RoomLocationId");
                });

            modelBuilder.Entity("server.model.RoomsDB", b =>
                {
                    b.HasOne("server.model.RoomLocation", null)
                        .WithMany("ListRooms")
                        .HasForeignKey("RoomLocationId");
                });

            modelBuilder.Entity("server.model.Registereds", b =>
                {
                    b.Navigation("ListConditions");

                    b.Navigation("ListOptions");
                });

            modelBuilder.Entity("server.model.RoomLocation", b =>
                {
                    b.Navigation("ListRegistereds");

                    b.Navigation("ListRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
