// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(MyHotelDbContext))]
    partial class MyHotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("server.Model.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid?>("RegisteredsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredsId");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("server.Model.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Num")
                        .HasColumnType("int");

                    b.Property<int>("idNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("server.model.PricesList", b =>
                {
                    b.Property<Guid>("IdPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid?>("RegisteredsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPrice");

                    b.HasIndex("RegisteredsId");

                    b.ToTable("PricesLists");
                });

            modelBuilder.Entity("server.model.PricesListHistory", b =>
                {
                    b.Property<Guid>("IdHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdPrice")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("IdHistory");

                    b.ToTable("PricesListHistories");
                });

            modelBuilder.Entity("server.model.Registereds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SumPlace")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomLocationId");

                    b.ToTable("Registereds");
                });

            modelBuilder.Entity("server.model.RoomDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Extrta")
                        .HasColumnType("bit");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Occupied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnSea")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RoomLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoomNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomLocationId");

                    b.ToTable("RoomsDBs");
                });

            modelBuilder.Entity("server.model.RoomLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoomLocations");
                });

            modelBuilder.Entity("server.Model.Condition", b =>
                {
                    b.HasOne("server.model.Registereds", null)
                        .WithMany("ListConditions")
                        .HasForeignKey("RegisteredsId");
                });

            modelBuilder.Entity("server.model.PricesList", b =>
                {
                    b.HasOne("server.model.Registereds", null)
                        .WithMany("ListOptions")
                        .HasForeignKey("RegisteredsId");
                });

            modelBuilder.Entity("server.model.Registereds", b =>
                {
                    b.HasOne("server.model.RoomLocation", null)
                        .WithMany("ListRegistereds")
                        .HasForeignKey("RoomLocationId");
                });

            modelBuilder.Entity("server.model.RoomDB", b =>
                {
                    b.HasOne("server.model.RoomLocation", null)
                        .WithMany("ListRooms")
                        .HasForeignKey("RoomLocationId");
                });

            modelBuilder.Entity("server.model.Registereds", b =>
                {
                    b.Navigation("ListConditions");

                    b.Navigation("ListOptions");
                });

            modelBuilder.Entity("server.model.RoomLocation", b =>
                {
                    b.Navigation("ListRegistereds");

                    b.Navigation("ListRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
